CREATE DATABASE Account_Management_System;
 go

 USE Account_Management_System;
 go

CREATE Table [User](
UserID BIGINT IDENTITY(1,1) PRIMARY KEY,
UserName NVARCHAR(250) NOT NULL,
DOB DATETIME NOT NULL,
DOJ DATETIME NOT NULL,
Balance DECIMAL(10,6),
MobileNo INT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT getdate()
);
go

CREATE TABLE [Account](
AccountID BIGINT IDENTITY(1,1) PRIMARY KEY,
AccountNo INT NOT NULL,
IsSaving BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
Created DATETIME NOT NULL DEFAULT getdate()
);
go

CREATE TABLE [UserAccountMapping](
UserAccountMapping BIGINT IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL FOREIGN KEY REFERENCES[User],
AccountNo BIGINT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
Created DATETIME NOT NULL DEFAULT getdate()
);
go

CREATE TABLE [Address](
AddressID BIGINT IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL FOREIGN KEY REFERENCES[User],
Address  NVARCHAR(max) NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
Created DATETIME NOT NULL DEFAULT getdate()
);
go

CREATE TABLE [AccountTransaction](
AccountTransaction BIGINT IDENTITY(1,1) PRIMARY KEY,
Amount DECIMAL(10,6) NOT NULL,
IsDEBIT BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
Created DATETIME NOT NULL DEFAULT getdate()
); 
go