USE TEST;

CREATE TABLE [User](
UserID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserName NVARCHAR(250) NOT NULL,
DOB DATETIME NOT NULL,
DOJ DATETIME NOT NULL, 
Balance DECIMAL(10,6) Null,
MobileNo INT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
)


CREATE TABLE Account(
AccountID BIGINT NOT NUll  IDENTITY(1,1) PRIMARY KEY,
AccountNo INT NOT NULL,
IsSaving BIT NOT NULL ,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
)


CREATE TABLE UserAccountMapping(
UserAccountMapping BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL ,
FOREIGN KEY(UserID) REFERENCES [User](UserID),
AccountID BIGINT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL ,
CreatdeDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Address (
AdressID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL,
FOREIGN KEY(UserID) REFERENCES [User](USerID),
Address NVARCHAR(max) NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
)

CREATE TABLE AccountTransaction (
AccountTransaction BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Amount DECIMAL(10,6) NOT NULL,
IsDebit BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
)