CREATE DATABASE AccountManagementSystem;
go

USE  AccountManagementSystem;
go
CREATE TABLE [User](
UserID BIGINT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
UserName NVARCHAR(250)  NOT NULL,
DOB DATETIME  NOT NULL,
DOJ DATETIME  NOT NULL,
Balance DECIMAL(10,6),
MobileNo BIGINT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME DEFAULT getdate() NOT NULL
);
go


CREATE TABLE [Account](
AccountID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
AccountNo INT NOT NULL,
IsSaving BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME DEFAULT getdate() NOT NULL
);

go


CREATE TABLE [UserAccountMapping](
UserAccountmapping BIGINT IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL FOREIGN KEY REFERENCES [User](UserID),
AccountID BIGINT NOT NULL,
CreatedBy VARCHAR(250)  NOT NULL,
CreatedDate DATETIME DEFAULT getdate() NOT NULL
);
go



CREATE TABLE [Address](AddressID BIGINT IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL  FOREIGN KEY REFERENCES [User](UserID),
Address NVARCHAR(max)  NOT NULL,
CreatedBy VARCHAR(250)  NOT NULL,
CreatedDate DATETIME DEFAULT getdate() NOT NULL
);
go


CREATE TABLE [AccountTransaction](AccountTransaction BIGINT IDENTITY(1,1) PRIMARY KEY,
Amount DECIMAL(10,6)NOT NULL,
IsDebit BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME DEFAULT getdate() NOT NULL
);




