CREATE DATABASE AccountManagementSystem
GO

USE AccountManagementSystem
GO

CREATE SCHEMA AMS;
GO

CREATE TABLE AMS.[User](
UserID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserName NVARCHAR(250) NOT NULL,
DateOfBirth DATETIME NOT NULL,
DateOfJoining DATETIME NOT NULL,
Balance DECIMAL(10,6) NULL,
MobileNumber INT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);

SELECT * from AMS.[User]

CREATE TABLE AMS.[Account](
AccountID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
AccountNumber INT NOT NULL,
IsSaving BIT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);

SELECT * from AMS.[Account]

CREATE TABLE AMS.[UserAccountMapping](
UserAccountMappingID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserID BIGINT NOT NULL,
AccountID BIGINT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),

CONSTRAINT FK_UserAccountMapping_User FOREIGN KEY (UserID)
REFERENCES AMS.[User](UserID),
CONSTRAINT FK_UserAccountMapping_Account FOREIGN KEY (AccountID)
REFERENCES AMS.[Account](AccountID)
);

SELECT * from AMS.[UserAccountMapping]

CREATE TABLE AMS.[Address](
AddressID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserID BIGINT NOT NULL,
FullAddress NVARCHAR(MAX) NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),

CONSTRAINT FK_Address_User FOREIGN KEY (UserID)
REFERENCES AMS.[User](UserID)
);

SELECT * from AMS.[Address]

CREATE TABLE AMS.[AccountTransaction](
AccountTransactionID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
AccountID BIGINT NOT NULL,
Amount DECIMAL(10,6) NOT NULL,
IsDebit BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),

CONSTRAINT FK_AccountTransaction_Account FOREIGN KEY (AccountID)
REFERENCES AMS.[Account](AccountID)
);

SELECT * from AMS.[AccountTransaction]
