CREATE DATABASE BankDba;
go
USE BankDba;
go
CREATE TABLE [User](
UserID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserName NVARCHAR(250) NOT NULL,
DOB DATETIME NOT NULL,
DOJ DATETIME NOT NULL,
Balance DECIMAL(10,6) NOT NULL,
MobileNo INT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
go

SELECT * FROM [User];

CREATE TABLE [Account](
AccountID BIGINT IDENTITY(1,1) NOT NULL,
AccountNo INT NOT NULL,
IsSaving BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
go
SELECT * FROM [Account];

ALTER TABLE [Account]
ADD CONSTRAINT pk_AccountId PRIMARY KEY(AccountId); 
go

CREATE TABLE [UserAccountMapping](
UserAccountMapping BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserID BIGINT NOT NULL,
AccountId BIGINT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
FOREIGN KEY (UserID) REFERENCES [User](UserID)
);
go

SELECT * FROM [UserAccountMapping];

CREATE TABLE [Address](
AddressID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
UserId BIGINT NOT NULL,
Address NVARCHAR(MAX) NOT NULL,
CreatedBY VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
FOREIGN KEY (UserId) REFERENCES [User](UserID)
);
go

SELECT * FROM [Address];

CREATE TABLE [AccountTransaction](
AccountTransaction BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Amount Decimal(10,6) NOT NULL,
IsDebit Bit NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);

go

SELECT * FROM [AccountTransaction];