CREATE TABLE Userr (
    UserID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(250) NOT NULL,
    DOB DATETIME NOT NULL,
    DOJ DATETIME NOT NULL,
    Balance DECIMAL(10,6) NULL,
    MobileNo INT NOT NULL,
    CreatedBy VARCHAR(250) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);

select * from Userr
