CREATE DATABASE DB;
GO
USE DATABASE DB;
GO
CREATE SCHEMA SC;
GO


    



CREATE TABLE SC.[User] (
    UserID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(250) NOT NULL,
    DOB DATETIME NOT NULL,
    DOJ DATETIME NOT NULL,
    Balance DECIMAL(10, 6) NULL,
    MobileNo INT NOT NULL,
    CreatedBy VARCHAR(250) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
go

CREATE TABLE SC.[Account] (
    AccountID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    AccountNo INT NOT NULL,
    IsSaving BIT NOT NULL,
    CreatedBy VARCHAR(250) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
go
CREATE TABLE SC.[UserAccountMapping] (
    UsrerAccountMapping BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserID BIGINT NOT NULL,
    AccountID BIGINT NOT NULL,
    CreatedBy VARCHAR(250) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES [User](UserID),
    FOREIGN KEY (AccountID) REFERENCES Account(AccountID)
);

go
CREATE TABLE SC.Address (
    AddressID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserID BIGINT NOT NULL,
    Address NVARCHAR(MAX) NOT NULL,
    CreatedBy VARCHAR(250) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES [User](UserID)
);
