CREATE TABLE Address (
	AddressID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID BIGINT NOT NULL,
	Address NVARCHAR(MAX) NOT NULL,
	CreatedBy VARCHAR(250) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
SELECT * FROM Account