CREATE TABLE Account (
	AccountID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	AccountNo INT NOT NULL,
	IsSaving BIT NOT NULL,
	CreatedBy VARCHAR(250) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
SELECT * FROM Account