CREATE TABLE UserAccountMapping(
	UserAccountMappingID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID BIGINT NOT NULL,
	AccountID BIGINT NOT NULL,
	CreatedBy VARCHAR(250) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	FOREIGN KEY (AccountID) REFERENCES Account(AccountID),
);
SELECT * FROM UserAccountMapping