CREATE DATABASE BankingAssign1

CREATE TABLE [User]
(UserID BIGINT  NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserName NVARCHAR(250)  NOT NULL,
DOB DATETIME NOT NULL,
DOJ DATETIME NOT NULL,
Balance DECIMAL(10,6),
MobileNumber INT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
);

SELECT * FROM [User];


CREATE TABLE [Account]
(AccountID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
AccountNo INT NOT NULL,
IsSaving BIT NOT NULL,
CreatedBy VARCHAR NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
);
SELECT * FROM [Account]
CREATE TABLE [UserAccMapping](
UserAccountMapping BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserID  BIGINT NOT NULL,
AccountID BIGINT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
CONSTRAINT [FK_UserID] FOREIGN KEY (UserID) REFERENCES[User](UserID),
);
SELECT * FROM[UserAccMapping]
CREATE TABLE [Address]
(AddressID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
UserID BIGINT NOT NULL,
Address NVARCHAR(50) NOT NULL,
CreatedBy VARCHAR(50) NOT  NULL,
CreatedDate DATETIME DEFAULT GETDATE(),
CONSTRAINT [FK_UserID] FOREIGN KEY (UserID) REFERENCES [User](UserID),
);
SELECT * FROM [Address]
CREATE TABLE [AccountTransaction]
(AccountTransaction BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Amount DECIMAL(10,6) NOT NULL,
IsDebit BIT NOT NULL,
CreatedBy VARCHAR(250) NOT NULL,
CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
);

SELECT * FROM [AccountTransaction]