CREATE TABLE [Emp] (
    [EmpId] INT NOT NULL IDENTITY(1, 1),
    [Name] VARCHAR(255) NULL,
    [DeptId] INT NULL,
    [Salary] INT NULL,
    PRIMARY KEY ([EmpID])
);
GO
TRUNCATE TABLE [Emp]
INSERT INTO [Emp] ([Name], DeptId, Salary)
VALUES
  ('Britanni',3,1000),
  ('Julian',2,2000),
  ('Dolan',3,3000),
  ('Jonah',4,4000),
  ('Fulton',2,5000),
  ('Scarlett',4,1000),
  ('Bernard',2,2000),
  ('Chancellor',1,3000),
  ('Dalton',4,4500),
  ('Len',1,5000),
  ('Bree',4,1000),
  ('Cooper',1,2000),
  ('Nora',4,3000),
  ('Gareth',3,4000),
  ('Beau',2,5000);  

SELECT *,
  ROW_NUMBER() OVER(PARTITION BY DEPTID ORDER BY SALARY) AS ROWNUMBER,
  RANK() OVER(PARTITION BY DEPTID ORDER BY SALARY) AS [RANK],
  DENSE_RANK() OVER(PARTITION BY DEPTID ORDER BY SALARY) AS [DENSERANK]
FROM [dbo].[EMP];


SELECT *,
  ROW_NUMBER() OVER(ORDER BY SALARY) AS ROWNUMBER,
  RANK() OVER(ORDER BY SALARY) AS [RANK],
  DENSE_RANK() OVER(ORDER BY SALARY) AS [DENSERANK]
FROM [dbo].[EMP];

ALTER TABLE EMP
ADD  DOB DATE NULL;

UPDATE EMP SET DOB = '2003-01-01' WHERE EMPID IN (1,2,5,12);
UPDATE EMP SET DOB = '2003-01-01' WHERE EMPID IN (8,10,7,15);

WITH RANKEDBYYEAR AS
(
    SELECT *, 
        YEAR(DOB) AS dateBirth,
        RANK() OVER (PARTITION BY YEAR(DOB) ORDER BY SALARY DESC) AS RANKBYYEAR,
        DENSE_RANK() OVER (PARTITION BY YEAR(DOB) ORDER BY SALARY DESC) AS DENSERANK,
        ROW_NUMBER() OVER (PARTITION BY YEAR(DOB) ORDER BY SALARY DESC) AS ROWNUM
    FROM EMP
)
SELECT * FROM RANKEDBYYEAR;

-- RANK FUNCTION IN AMS.[AccountAnalysis]
with CTE_Name as
(
      select year(u.DOB) as YEAR_Col , u.Balance as BALANCE from AMS.[AccountAnalytics] u
)

select * ,
ROW_NUMBER() OVER(PARTITION BY YEAR_COL ORDER BY BALANCE) As RowNumber,
RANK() OVER(PARTITION BY YEAR_COL ORDER BY BALANCE) As [Rank],
DENSE_RANK() OVER(PARTITION BY YEAR_COL ORDER BY BALANCE) As [DenseRank]
From CTE_Name;


